#!/bin/bash
set -euo pipefail

# ------------------------------------------------------------------
# Install dependencies of setup_castle_engine specific
# in a GitHub-hosted or GitLab-hosted runner.
#
# Execute this only on GitHub/GitLab-hosted ephemeral runner where you have
# root permissions to install packages (and you should install them
# every time the workflow is performed).
# ------------------------------------------------------------------

if which apt-get > /dev/null 2>&1; then
  echo "Installing Linux dependencies"

  # On GitLab CI, execute without sudo.
  if which sudo > /dev/null 2>&1; then
    SUDO=sudo
  else
    SUDO=
  fi

  $SUDO apt-get update
  # See https://castle-engine.io/compiling_from_source.php behind
  # some of the dependencies like libgtk2.0-dev .
  $SUDO apt-get install -y wget libgtk2.0-dev
fi

if which choco > /dev/null 2>&1; then
  echo "Installing Windows dependencies"
  choco install wget
fi

if which brew > /dev/null 2>&1; then
  echo "Installing macOS dependencies"
  # No need, wget is already installed on macOS runners.
  # brew install wget
fi
