#!/usr/bin/env bash
set -euo pipefail

# ------------------------------------------------------------------
# Install dependencies of setup_castle_engine specific
# in a GitHub-hosted or GitLab-hosted runner.
#
# Execute this only on GitHub/GitLab-hosted ephemeral runner where you have
# root permissions to install packages (and you should install them
# every time the workflow is performed).
# ------------------------------------------------------------------

if command -v apt-get > /dev/null 2>&1; then
  echo "Installing Linux dependencies"

  # On GitLab CI, execute without sudo.
  if command -v sudo > /dev/null 2>&1; then
    SUDO=sudo
  else
    SUDO=
  fi

  $SUDO apt-get update
  # See https://castle-engine.io/compiling_from_source.php behind
  # some of the dependencies like libgtk2.0-dev .
  # TODO: For now, we install both GTK 2 and 3 dependencies,
  # as we're switching GTK 2 -> 3.
  $SUDO apt-get install -y wget libgtk2.0-dev libgl-dev libgtk-3-dev
fi

if command -v choco > /dev/null 2>&1; then
  echo "Installing Windows dependencies"
  # --no-progress avoids too verbose progress output in CI logs.
  choco install --no-progress wget
fi

if command -v brew > /dev/null 2>&1; then
  echo "Installing macOS dependencies"
  # No need, wget is already installed on macOS runners.
  # brew install wget
fi
