#!/bin/bash
set -euo pipefail

# ------------------------------------------------------------------
# Install dependencies of setup_castle_engine specific to GitHub-hosted runner.
# Execute this only on GH-hosted ephemeral runner where you have
# root permissions to install packages (and you should install them
# every time the workflow is performed).
# ------------------------------------------------------------------

if which apt-get > /dev/null; then
  echo "Installing Linux dependencies"
  sudo apt-get update
  sudo apt-get install -y wget libgtk2.0-dev
fi

if which choco > /dev/null; then
  echo "Installing Windows dependencies"
  choco install wget
fi

if which brew > /dev/null; then
  echo "Installing macOS dependencies"
  # No need, wget is already installed on macOS runners.
  # brew install wget
fi
