#!/bin/bash
set -euo pipefail

# -----------------------------------------------------------------------------
# Use this script to easily setup
# - FPC (Free Pascal Compiler)
# - and CGE (Castle Game Engine)
#
# Arguments: OS and CPU, in the FPC naming conventions.
# Like "setup_castle_engine linux x86_64" .
#
# Current directory when this is called matters:
# we assume it is the workspace, we will create fpc/ and castle-engine/ subdirs
# there.
#
# After this is called, calling "castle-engine package" will package your project.
# It enhances the PATH variable to include FPC and CGE build tool
# by enhancing file $GITHUB_ENV (if defined) and setup_castle_engine_env.sh
# (the latter useful for non-GitHub Action CI).
#
# Details what it does:
#
# - Get and setup FPC recommended to use with CGE.
#
#   This downloads FPC (to fpc/ subdir) from our
#   https://github.com/castle-engine/castle-fpc releases
#   which have prebuild FPC binary + FPC sources.
#   And sets up fpc.cfg to use it properly (see castle-fpc/README.md docs).
#
# - Get and setup CGE in recommended way for CI/CD.
#
#   This downloads CGE sources from the "snapshot" tag
#   (latest engine that passed automatic tests)
#   and builds our build tool ("castle-engine")
#   and sets CASTLE_ENGINE_PATH and PATH to put it on PATH.
# -----------------------------------------------------------------------------

OS=$1
CPU=$2
shift 2

#CASTLE_ENGINE_VERSION='snapshot'
# TODO: just a test while LSOpenCFURLRef is in the process of being tested
CASTLE_ENGINE_VERSION='master'

# ----------------------------------------------------------------------------
# bash functions

# Preserve variable named $1 for future CI steps.
# Uses $GITHUB_ENV (if defined, in GitHub Actions) and to setup_castle_engine_env.sh.
preserve_variable_for_future_ci_steps()
{
  VAR=$1
  shift 1

  if [ -n "${GITHUB_ENV:-}" ] ; then
    if [ -d "`dirname \"${GITHUB_ENV}\"`" ] ; then
      echo "$VAR=${!VAR}" >> "${GITHUB_ENV}"
    else
      echo "Warning: GITHUB_ENV is defined (${GITHUB_ENV}), but the directory it points to doesn't exist."
      echo "  Possible reason: you are within GitHub Actions job and use pguyot/arm-runner-action, where GITHUB_ENV refers to outer machine (like ubuntu-latest), not the ARM runner machine."
      echo "  Ignoring GITHUB_ENV."
    fi
  fi

  # Add export and surround with ', to allow "source setup_castle_engine_env.sh" reliably
  echo "export $VAR='${!VAR}'" >> "${DEFINES_FILE}"
}

# Determine variables used in the rest of the script.
do_setup_environment()
{
  # calculate WORKSPACE_ROOT and WORKSPACE_ROOT_UNIX.
  # On Windows they differ:
  # - WORKSPACE_ROOT_UNIX is in Cygwin path format (with /, without :, more suitable for $PATH)
  # - WORKSPACE_ROOT is in native (on Windows) path format, understood also by non-Msys2/Cygwin tools
  WORKSPACE_ROOT_UNIX="`pwd`"
  WORKSPACE_ROOT="${WORKSPACE_ROOT_UNIX}"
  if which cygpath > /dev/null; then
    WORKSPACE_ROOT="`cygpath --mixed \"${WORKSPACE_ROOT}\"`"
  fi

  DEFINES_FILE="${WORKSPACE_ROOT}/setup_castle_engine_env.sh"
}

# Just in case, enable multiple runs of this script, by cleaning up
# at the beginning.
do_cleanup()
{
  rm -Rf fpc/ castle-engine/ "${DEFINES_FILE}"
}

# Get FPC from castle-fpc
do_get_fpc()
{
  echo '-------------------------------------------------------------------'
  echo 'Setting up FPC'

  # Use PPC_CONFIG_PATH to provide custom fpc.cfg
  # in a way that is cross-platform (otherwise, we'd need to use ~/.fpc.cfg
  # on Unix, fpc/bin/ on Windows) and that doesn't mess with any user/system-wide
  # fpc.cfg (so e.g. we don't touch ~/.fpc.cfg on user's machine).

  export PPC_CONFIG_PATH="${WORKSPACE_ROOT}/fpc"
  preserve_variable_for_future_ci_steps PPC_CONFIG_PATH
  FPC_CFG="${PPC_CONFIG_PATH}/fpc.cfg"

  # export PATH="${WORKSPACE_ROOT_UNIX}/fpc/bin:${PATH}"
  preserve_variable_for_future_ci_steps PATH
}

# Get Castle Game Engine
do_get_castle_engine()
{
  export CASTLE_ENGINE_PATH="${WORKSPACE_ROOT}/castle-engine"
  # Note that below we needto use WORKSPACE_ROOT_UNIX, not WORKSPACE_ROOT,
  # which is important on Windows: inside Msys2/Cygwin, we need to use
  # Unix path format (with /, without : for drive separator, as : is used
  # to separate multiple entries in PATH).
  #export PATH="${WORKSPACE_ROOT_UNIX}/castle-engine/tools/build-tool/:${PATH}"

  preserve_variable_for_future_ci_steps CASTLE_ENGINE_PATH
  preserve_variable_for_future_ci_steps PATH
}

# ----------------------------------------------------------------------------
# main: call functions

# do_setup_environment
# do_cleanup
# do_get_fpc
# do_get_castle_engine

preserve_variable_for_future_ci_steps PATH