#!/usr/bin/env bash
set -euo pipefail

# -----------------------------------------------------------------------------
# Validate correctness of scripts here:
# run shellcheck on all shell script files here.
# -----------------------------------------------------------------------------

find . \
  '(' -type d -name '.git' -prune ')' -or \
  '(' -type f -path './test_project/test_project' ')' -or \
  '(' -type f -perm /111 -print0 ')' | while read -rd $'\0' FILE; do
  shellcheck "$FILE"
done
