#!/bin/bash
set -euo pipefail

# ------------------------------------------------------------------------------
# Setup keychain with proper certificate, to execute sign_bundle later.
# Saves temp stuff in $RUNNER_TEMP (defined in GitHub Actions runners)
# or /tmp.
# This doesn't clean up after itself -- assumes ephemeral CI runner will
# be cleaned up.
#
# See https://docs.github.com/en/actions/how-tos/deploy/deploy-to-third-party-platforms/sign-xcode-applications .
# ------------------------------------------------------------------------------

if [ -n "${RUNNER_TEMP:-}" ] ; then
  TEMP_DIR="${RUNNER_TEMP}"
else
  TEMP_DIR="/tmp"
fi

# create variables
CERTIFICATE_PATH="${TEMP_DIR}/build_certificate.p12"
KEYCHAIN_PATH="${TEMP_DIR}/app-signing.keychain-db"
# provisioning (only for mobile targets, not for macOS)
#PP_PATH="${TEMP_DIR}/build_pp.mobileprovision"

# import certificate and provisioning profile from secrets
echo -n "${APPLE_BUILD_CERTIFICATE_BASE64}" | base64 --decode -o "${CERTIFICATE_PATH}"
# provisioning (only for mobile targets, not for macOS)
#echo -n "${APPLE_BUILD_PROVISION_PROFILE_BASE64}" | base64 --decode -o "${PP_PATH}"

# create temporary keychain
security create-keychain -p "${APPLE_KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
security set-keychain-settings -lut 21600 "${KEYCHAIN_PATH}"
security unlock-keychain -p "${APPLE_KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"

# import certificate to keychain
security import "${CERTIFICATE_PATH}" -P "${APPLE_P12_PASSWORD}" -A -t cert -f pkcs12 -k "${KEYCHAIN_PATH}"
security set-key-partition-list -S apple-tool:,apple: -k "${APPLE_KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
security list-keychain -d user -s "${KEYCHAIN_PATH}"

# apply provisioning profile (only for mobile targets, not for macOS)
#mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
#cp "${PP_PATH}" ~/Library/MobileDevice/Provisioning\ Profiles
